# Generated by Django 4.0.5 on 2023-10-30 16:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_pedido_precio_total_pedido_precio_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=255, unique=True, verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='El precio no puede ser negativo')], verbose_name='Cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor',
            },
        ),
        migrations.AlterUniqueTogether(
            name='coleccionproducto',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coleccionproducto',
            name='coleccion',
        ),
        migrations.RemoveField(
            model_name='coleccionproducto',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Coleccion',
        ),
        migrations.DeleteModel(
            name='ColeccionProducto',
        ),
    ]
