# Generated by Django 4.0.5 on 2023-10-30 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_proveedor_proveedorproducto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedorproducto',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='proveedorproducto',
            name='fecha',
            field=models.DateField(default=datetime.date(2023, 10, 30), verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='proveedorproducto',
            name='hora',
            field=models.DateTimeField(default=datetime.date(2023, 10, 30), verbose_name='Hora'),
        ),
    ]
