# Generated by Django 4.0.5 on 2023-10-30 16:22

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_proveedorproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorproducto',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='proveedorproducto',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora'),
        ),
    ]
