# Generated by Django 4.0.5 on 2023-10-30 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_proveedorproducto_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='hora',
        ),
        migrations.CreateModel(
            name='HistorialProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('proveedor_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedorproducto', verbose_name='Proveedor')),
            ],
        ),
    ]
